# Generated by Django 2.0.2 on 2019-01-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=20)),
                ('pack_price', models.PositiveIntegerField(default=10)),
                ('fruit_pic', models.ImageField(upload_to='offer/', verbose_name='Fruit Photo')),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
