# Generated by Django 2.0.2 on 2019-03-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190218_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='apa123', max_length=7),
            preserve_default=False,
        ),
    ]
